### ISSUE TITLE
看了多渠道打包更换icon过来的

### ISSUE THREAD

**Issue by ViolentBanana** [Wing-Li/boon#1]
在manifest中替换了
`<application
    android:icon="${app_icon}"
    android:label="@string/app_name"
    android:theme="@style/AppTheme">
    ...
    <meta-data
        android:name="UMENG_CHANNEL"
        android:value="${ENVIRONMENT}" />
    ...
</application>`

其中icon替换为如上代码，直接报错，无法运行

**Comment by Wing-Li** [comment]
抱歉，回复的有点迟。
怎么感觉好像没收到邮箱。
-------------------------------------------------

我修改了项目，刚提交了。
你重新下载一下，可以看到。
我测试过了，打出的包，安装图标是不同的。

或者直接看我最新的提交记录，跟你哪里不一样。
[最新提交记录](https://github.com/Wing-Li/boon/commit/517203260e5ad1f62b76e446755f9bd1a87888ed)
