### ISSUE TITLE
为什么我的编译不通过

### ISSUE THREAD

**Issue by 2318423730** [Wing-Li/boon#2]
productFlavors复制到自己项目后
Error:Execution failed for task ':app:processCmxDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by Wing-Li** [comment]
还有更多的提示信息吗？

compile 导入 com.android.support 官方的包的版本号是不是一致的？

这个是我搜到的。
https://stackoverflow.com/questions/45134998/execution-failed-for-task-appprocessdebugmanifest-android-studio-2-3-3

https://stackoverflow.com/questions/46281144/errorexecution-failed-for-task-appprocessdebugmanifest-in-android-studio

**Comment by 2318423730** [comment]
我刚刚找到原因了 AndroidManifest中有几个权限重复添加了
