### ISSUE TITLE
编译不通过呀

### ISSUE THREAD

**Issue by wangfumm** [Wing-Li/boon#3]
Build Config field cannot have a null parameter
刚开始是报goole()

**Comment by Wing-Li** [comment]
现在报什么？

**Comment by bairenxing** [comment]
![20181029094032](https://user-images.githubusercontent.com/25000427/47625221-c4cd5580-db5e-11e8-8e7a-a9d0c1b37895.png)
作者，是这个问题

**Comment by Wing-Li** [comment]
在项目根目录的 local.properties 文件里添加下面这个参数

`appIdMark=""`

因为 build.gradle 中用到了。
